name: messaging-app
version: 0.1
summary: Messaging application for Ubuntu
description: Messaging application for Ubuntu
confinement: devmode  # use "strict" to enforce system access only via declared interfaces
grade: devel

apps:
    messaging-app:
        command: desktop-launch $SNAP/usr/bin/messaging-app --desktop_file_hint=unity8 "$@"
        plugs: [unity7, opengl, platform, gsettings]

plugs:
    platform:
        interface: content
        content: ubuntu-app-platform1
        target: ubuntu-app-platform
        default-provider: ubuntu-app-platform

parts:
    messaging-app:
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
        source: .
        build-packages:
            - cmake
            - intltool
            - pkg-config
            - libnotify-dev
            - qt5-default
            - qtbase5-dev
            - qtdeclarative5-dev
            - qtdeclarative5-dev-tools
            - qtmultimedia5-dev
            - qtpim5-dev

        stage-packages:
            - qtdeclarative5-ubuntu-addressbook0.1
            - qtdeclarative5-ubuntu-history0.1
            - qtdeclarative5-ubuntu-telephony-phonenumber0.1
            - qtdeclarative5-ubuntu-telephony0.1

        snap:
            - -usr/lib/python3
            - -usr/share/doc
            - -usr/include         

        after: [desktop-ubuntu-app-platform]

    environment:
        source: snap/
        plugin: dump
